INSERT INTO soldier_type (name_of_type, type_rank)
VALUES
    ('Soldier', 0),
    ('Corporal', 1),
    ('Ensign', 2),
    ('Sergeant', 3),
    ('Foreman', 4),
    ('Lieutenant', 5),
    ('Captain', 6),
    ('Major', 7),
    ('Lieutenant Colonel', 8),
    ('Colonel', 9),
    ('General', 10);

INSERT INTO subdivision_type(name_of_type, type_rank)
VALUES
    ('Squad', 0),
    ('Platoon', 1),
    ('Rota', 2),
    ('Military Unit', 3),
    ('Corps', 4),
    ('Brigade', 4),
    ('Division', 4),
    ('Army', 5);

-- Inserting data into mas_type table
INSERT INTO mas_type (code_of_mas, name_of_mas) VALUES
    ('00201', 'Operation and repair of engineering vehicles'),
    ('01000', 'Medical service in ground forces (general practitioner)'),
    ('01001', 'Combat use of engineer-sapper units and formations'),
    ('01001', 'Commander of engineer-sapper unit or combat use of engineer-sapper units and formations'),
    ('021000', 'Commander of motorized rifle platoon or Combat use of motorized rifle units, formations, and associations'),
    ('021001', 'Combat use of motorized rifle units, parts on BMP'),
    ('021002', 'Combat use of motorized rifle units, military units, and formations on BTR (vehicles)'),
    ('021101', 'Combat use of medium tank units or Combat use of medium tank units, parts'),
    ('0300', 'Organization of food supply'),
    ('030403', 'Combat use of units and parts of regimental and divisional artillery. May hold positions: commander of fire platoon, commander of control platoon, commander of mortar platoon'),
    ('030403', 'Combat use of units and military units of regimental and divisional artillery'),
    ('030404', 'Combat use of units and military units of anti-tank artillery'),
    ('030405', 'Combat use of mortar units, parts, and formations. May hold positions: commander of fire platoon, commander of control platoon, commander of mortar platoon'),
    ('030405', 'Combat use of mortar units, parts, and formations'),
    ('037', 'Commander of BM Strela-10'),
    ('041800', 'Combat use of units and military units armed with short-range air defense systems (Strela-10)'),
    ('041900', 'Combat use of units and military units armed with short-range air defense systems (Igla)'),
    ('043203', 'Combat use of starting units of multi-channel medium-range air defense systems'),
    ('06008', 'Technical personnel'),
    ('062600', 'Flight personnel'),
    ('072301', 'Navigator of diesel submarines'),
    ('08600', 'Organization of humanitarian training'),
    ('093500', 'Psychological warfare officer (with knowledge of a foreign language)'),
    ('094001', 'Combat use of ground reconnaissance units'),
    ('097001', 'Combat use of artillery reconnaissance units'),
    ('10003', 'Commander of engineering and technical platoon'),
    ('100097', 'Deputy platoon commander'),
    ('100182', 'Commander of motorized rifle squad'),
    ('100182', 'Commander of rifle squad'),
    ('100415', 'Signalman of motorized rifle troops'),
    ('100868', 'Senior gunner'),
    ('10101', 'Assistant commander of a military unit for financial and economic work or Financial support and economics of combat and economic activities'),
    ('101001', 'Commander of engineer-sapper unit or combat use of engineer-sapper units and formations'),
    ('101002', 'Combat use of engineering barrier and obstruction units and military units'),
    ('101004', 'Use of engineering and camouflage units and military units'),
    ('10200', 'Field bank organization worker for emission-cash, accounting-operational, credit work, and foreign currency operations or similar work'),
    ('10201', 'Operation and repair of radiation and chemical reconnaissance means'),
    ('10203', 'Operation and repair of chemical protection and special treatment troops'),
    ('103061', 'Hand-held anti-tank grenade launcher gunner'),
    ('104182', 'Commander of MANPADS unit Igla'),
    ('106147', 'Commander of reconnaissance unit'),
    ('106182', 'Reconnaissance unit commander'),
    ('106097', 'Deputy commander of reconnaissance unit'),
    ('106646', 'Reconnaissance scout'),
    ('107654', 'Diver-scout of special purpose units reconnaissance'),
    ('107746', 'Senior instructor in tactical and special training of special purpose units'),
    ('107847', 'Senior scout of special purpose military units'),
    ('111000', 'Use of units, military units, and formations of CBRN defense'),
    ('113194', 'Medium tank specialist — tank commander'),
    ('121000', 'Use of communication units, military units, and formations'),
    ('121100', 'Use of aviation communication units and parts and RTA'),
    ('121202', 'Use of units and military units with radio devices and medium-power radio stations'),
    ('121203', 'Use of units with low-power radio stations'),
    ('121301', 'Use of units and military units with multi-channel radio relay communication means'),
    ('121282', 'BMP-1 operator-gunner'),
    ('121400', 'Use of units and military units with low-channel radio relay and tropospheric communication means'),
    ('121702', 'Use of units and military units for operating long-distance communication means and cross devices'),
    ('122144', 'Commander of BMP platoon');
